### ISSUE TITLE
추가해야될거

### ISSUE THREAD

**Issue by rzbsys** [iwhale-team/gbl2022-backend#1]
### 고쳐야될 거

- [x] 1. 부스 점수 부여할때 사용자의 이름(name)도 받아서 같이 저장해야됨
- [x] 2. 모든 사용자의 점수를 불러올 때 이름도 반환해야됨
- [x] 3. 특정 유저 점수 불러올때 부스의 이름도 같이 반환해야됨

**Comment by iIIusi0n** [comment]
Done.
